apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: polls-frontend
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: cloud-native-polls
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    subPath: polls-frontend
    git:
      url: https://github.com/odedia/cloud-native-polls
      ref:
        branch: main
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq
