apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: polls-frontend
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: cloud-native-polls
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/odedia/cloud-native-polls
      ref:
        branch: main
  